GET http://localhost:5000

###

GET http://localhost:5000/order/all-orders

###

GET http://localhost:5000/order/specific-order/60a3acf14d8c473434e7e3e3

###

GET http://localhost:5000/order/user-orders/60a3acf14d8c473434e7e3e3

###

POST http://localhost:5000/order/add-order
Content-Type: application/json

{
    "ordernumber": "adsad12312", 
    "products": 
            [ 
              {
                "id":"60af85697d01c10cb0ad8e7f",
                "quantity": 2, 
                "size": 37    
              },
              {
                "id":"60af85697d01c10cb0ad8e7f",
                "quantity": 2, 
                "size": 38    
              },
              {
                "id":"60b0a393d609e00a4858a53c",
                "quantity": 2, 
                "size": 38   
              } 
            ],
    "customer": "60a79d8cbf69303b004dd159"
}

###

PATCH http://localhost:5000/order/sent-order/60a3acf14d8c473434e7e3e2

###