GET http://localhost:5000


###


GET http://localhost:5000/order/all-orders


###


GET http://localhost:5000/order/specific-order/60a3acf14d8c473434e7e3e3


###


GET http://localhost:5000/order/user-orders/60a3a7f76f6ca146c83a3183


###


POST http://localhost:5000/order/add-order
Content-Type: application/json

{
    "ordernumber": "adsad12312", 
    "product": 
            [
                "60a50ae8a847652544e0717d"
            ],
    "customer": "60a4fa6051ceee3f08a13335"
}


###

GET http://localhost:5000/order/order-products/60a4ddaa6fbe300c804bd6b7


###

PATCH http://localhost:5000/order/sent-order/60a4fa9751ceee3f08a13336
