GET http://localhost:5000


###


GET http://localhost:5000/order/all-orders


###


GET http://localhost:5000/order/specific-order/60a3808264eaa633ecf83c12


###

POST http://localhost:5000/order/add-order
Content-Type: application/json

{
    "ordernumber": "adsad12312", 
    "product": [
    {
        "name": "Nike air", 
        "price": 500, 
        "amount": 1, 
        "size": 45
    },
    {
         "name": "Puma dunka", 
        "price": 599, 
        "amount": 3, 
        "size": 42
    } 

    ],
    "customer": {
        "firstname": "Oliver",
        "lastname": "Johansson", 
        "adress": {
            "streetname": "Linnegatan 43", 
            "zip": 53431, 
            "city": "Göteborg"
        }
    }
}