POST http://localhost:5000/users/handleRegister
Content-Type: application/json

{
    "name": "Jakob",
    "adress": "Dahlströmsgatan 52",
    "phone": "0705773264",
    "email": "jakob@live.se",
    "password": "abc",
    "zip": "12345"
}

###

POST http://localhost:5000/users/handleLogin
Content-Type: application/json

{
    "email": "oliver@live.se",
    "password": "asd"
}

###

GET http://localhost:5000/users

###

DELETE http://localhost:5000/users/handleLogout