POST http://localhost:5000/users/handleRegister
Content-Type: application/json

{
    "name": "Adminmo",
    "adress": {
        "city": "Sweden",
        "street": "Göteborg",
        "zip": "12345"
    },
    "phone": "0705773264",
    "email": "admin@live.org",
    "password": "Testing123",
    "role": "admin"
}

###

POST http://localhost:5000/users/handleLogin
Content-Type: application/json

{
    "email": "admin@live.com",
    "password": "Testing112"
}


###

GET http://localhost:5000/users

###

DELETE http://localhost:5000/users/handleLogout

###

PUT http://localhost:5000/users/handleUpdate
Content-Type: application/json

{
    "name": "Peter",
    "adress": {
        "city": "Berlin",
        "street": "Sauerkraut 12",
        "zip": "12345"
    },
    "phone": "0705663266",
    "email": "peter@live.se"
}

###


GET http://localhost:5000/users/currentUser

###

PUT http://localhost:5000/users/handleRole/60b5f6b4dbc9351ba78c039b
Content-Type: application/json

{
    "role": "pending"
}