POST http://localhost:5000/image/uploadImage
Content-Type: multipart/form-data; boundary=Row

--Row
Content-Disposition: form-data; name="image"; filename="38a.jpg"
Content-Type: image/jpeg

< ./38a.jpg 
--Row--